# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usb_storage"
    "usbhid"
    "uas"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/ad24b844-2d89-485e-83d0-37dd86c8be5f";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-441b13c3-7421-4cd5-bc80-35f326e8bcb7".device =
    "/dev/disk/by-uuid/441b13c3-7421-4cd5-bc80-35f326e8bcb7";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/36B4-DE88";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/10137345-582b-4814-9be5-f46a3ed4e010";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-31ff715b-081d-40bf-a619-cac34feec0d9".device =
    "/dev/disk/by-uuid/31ff715b-081d-40bf-a619-cac34feec0d9";

  swapDevices = [
    { device = "/dev/disk/by-uuid/0015773b-4071-4860-831f-adbce0dbe308"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp37s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
